#!/bin/bash
################################################################################
# generate-inventory.sh — Auto-generate REPO-INVENTORY.md
# Sovereign Education Ecosystem
################################################################################

set -e

echo "⚡ Generating repository inventory..."
echo ""

OUTPUT_FILE="REPO-INVENTORY.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

# Start the inventory file
cat > "$OUTPUT_FILE" << 'HEADER'
# 📋 Repository Inventory

> Auto-generated inventory of all repositories in the Sovereign Education Ecosystem

**Generated:** TIMESTAMP_PLACEHOLDER  
**Total Repositories:** COUNT_PLACEHOLDER

---

HEADER

# Replace timestamp placeholder
sed -i "s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/" "$OUTPUT_FILE"

# Get all repos
repos=$(gh repo list Turbo-the-tech-dev --limit 100 --json name,description,updatedAt,isPrivate --jq '.[]')

repo_count=0

echo "## 📊 Repository List" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "| Repository | Description | Last Updated | Private |" >> "$OUTPUT_FILE"
echo "|------------|-------------|--------------|---------|" >> "$OUTPUT_FILE"

while IFS= read -r repo; do
    name=$(echo "$repo" | jq -r '.name')
    desc=$(echo "$repo" | jq -r '.description // "No description"')
    updated=$(echo "$repo" | jq -r '.updatedAt' | cut -d'T' -f1)
    private=$(echo "$repo" | jq -r '.isPrivate')
    
    if [ "$private" = "true" ]; then
        private_badge="🔒"
    else
        private_badge="🌍"
    fi
    
    echo "| [$name](https://github.com/Turbo-the-tech-dev/$name) | $desc | $updated | $private_badge |" >> "$OUTPUT_FILE"
    
    repo_count=$((repo_count + 1))
done <<< "$repos"

# Update count placeholder
sed -i "s/COUNT_PLACEHOLDER/$repo_count/" "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "---" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "*Generated by scripts/generate-inventory.sh*" >> "$OUTPUT_FILE"

echo "✅ Inventory generated: $OUTPUT_FILE"
echo "   Total repositories: $repo_count"
